### ISSUE TITLE
numpy does not work with msvc-static-install-only artefact

### ISSUE THREAD

**Issue by jheaff1** [indygreg/python-build-standalone#124]
Steps to reproduce:

1. Download the latest [msvc-static-install-only release](https://github.com/indygreg/python-build-standalone/releases/download/20220318/cpython-3.10.3+20220318-x86_64-pc-windows-msvc-static-install_only.tar.gz)
2. Extract the tarball
3. Run `python.exe -m pip install numpy`
4. Run `python.exe -c "import numpy"` and the following error is printed

<details>
  <summary>Console output</summary>
  

```
Traceback (most recent call last):
  File "C:\msys64\home\jheaff1\temp\temp\python\lib\site-packages\numpy\core\__init__.py", line 23, in <module>
    from . import multiarray
  File "C:\msys64\home\jheaff1\temp\temp\python\lib\site-packages\numpy\core\multiarray.py", line 10, in <module>
    from . import overrides
  File "C:\msys64\home\jheaff1\temp\temp\python\lib\site-packages\numpy\core\overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\msys64\home\jheaff1\temp\temp\python\lib\site-packages\numpy\__init__.py", line 144, in <module>
    from . import core
  File "C:\msys64\home\jheaff1\temp\temp\python\lib\site-packages\numpy\core\__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "C:\msys64\home\jheaff1\temp\temp\python\python.exe"
  * The NumPy version is: "1.22.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.
```

</details>

This issue does not occur with the msvc-shared-install-only artefact

**Comment by indygreg** [comment]
I'm going to say won't fix on this because the Windows static distributions are extremely brittle: https://python-build-standalone.readthedocs.io/en/latest/quirks.html#windows-static-distributions-are-extremely-brittle.

They sound like a good idea. But in reality nearly every non-trivial Python C extensions I've seen doesn't work with them unless they are recompiled from source. And even then, there are problems. Numpy's build process on Windows is especially thorny and I would expect it to fall in the camp of extensions that wouldn't work with our static builds without invasive changes to its build system.

I recommend most users steer clear of the Windows static distributions. Perhaps I should make this warning more visible in the docs linked earlier?

**Comment by jheaff1** [comment]
Many thanks for the explanation. I think the existing docs are sufficient 😁
