### ISSUE TITLE
Would be nice to have standalone pypy binaries

### ISSUE THREAD

**Issue by kingbuzzman** [indygreg/python-build-standalone#126]
_I recently discovered this repo, and I use it locally to give missing environments to [tox](https://github.com/tox-dev/tox)_. 

I realized that this repo lacks `pypy` binaries. I can't find any thread that's tried adding it, or anyone ever mentioning it. Can this be added? Is there a particular reason it hasn't been added?

**Comment by indygreg** [comment]
I haven't bothered with distributions other than CPython because I haven't perceived there to be a market need. Other Python distributions tend to already have a stronger story around more portable distributions because they are forced to (since they often aren't available in package managers since they are niche distributions).

Is there a compelling reason why you think this project should offer PyPy distributions?

**Comment by kingbuzzman** [comment]
To be frank, I haven't looked for pypy standalone distributions; I figured, if it would be under a single roof would be nice to have.

**Comment by kingbuzzman** [comment]
You're right, the prebuilt binaries are ready to go already [here](https://www.pypy.org/download_advanced.html). I also tested the mac and linux versions (inside docker) and they work like a charm. I'll close this.
