### ISSUE TITLE
Distribute archives without libpython3.9.a and stdlib's test packages 

### ISSUE THREAD

**Issue by tetsuok** [indygreg/python-build-standalone#134]
I realized that files extracted from `cpython-3.9.13+20220630-x86_64_v4-unknown-linux-gnu-install_only.tar.gz` contain  `libpython3.9.a` and [stdlib's test packages](https://github.com/indygreg/python-build-standalone/blob/5433319b133db67d20cb3aad5908165ab3768049/pythonbuild/cpython.py#L77). The total size of the static library and test packages is 56MB. This occupies 42% (= 56MB / 132MB) of these extracted files. It would be nice to distribute smaller archives without the static library and test packages. Users of [Bazel's Python rules](https://github.com/bazelbuild/rules_python) can take advantage of the smaller archives because they can build smaller Python build artifacts.

**Comment by indygreg** [comment]
FWIW there is an old issue somewhere discussing the sizes of the archives. I think it is the issue that resulted in the creation of the gzip compressed `install_only` archives. I recall that with zstd you don't really pay a penalty for the static archive because zstd is able to de-dupe the content since its compression window is so wide. But zlib has a 32 kb window to reuse data and you pay a heavy price for redundant large content. This is a big reason why the full zstd compressed archives are smaller than the gzip compressed install-only archives!

I can see a case for removing the static libpython from the `install_only` archives because I don't believe the static library should be used by many users in the wild: nearly everything in the Python ecosystem links against a dynamic libpython. Plus they have the full archives to download if they need this file.

The test files could potentially also be stripped from the `install_only` archives. I see that Linux distros also appear to not install these files by default. So that gives me some ammunition to justify the same. (Although Linux distros tend to package Python in... questionable ways, so I don't want to give credence to justifications that distro packagers use!)

**Comment by indygreg** [comment]
Going to close this since I believe it is fully implemented.

**Comment by tetsuok** [comment]
@indygreg Thank you very much!
