### ISSUE TITLE
help needed for python3.6 binary for linux / many_linux

### ISSUE THREAD

**Issue by printdhruv** [indygreg/python-build-standalone#143]
Hi @indygreg I was following instrctions to build python from (1) https://github.com/python/cpython/blob/3.6/README.rst  (2) https://testdriven.io/blog/bazel-builds/ 

I want to have standalone python3.6 binary in bazel environment. However, I tried various ways to build and import it into bazel environment but seems like running into various issues such as (1) No such file or directory : libffi.so (2) GLIBC version 2.xx and 2.xx not found but required from libm .

Is there any set of instructions you can provide to build python3.6 and use it into bazel workspace just the way you have other builds available.

**Comment by indygreg** [comment]
Unfortunately the earliest version of Python supported by this project was Python 3.7. It might be possible to get Python 3.6 working with this project. But this project's support for 3.7 was deleted nearly 2 years ago in c76ba72ad5484fcbccaa0cd1103a561fabffc008. A lot has changed since then and restoring support for even 3.7 against the current code is likely non-trivial.

Since Python 3.6 is out-of-support and will be a non-trivial amount of work to implement and maintain, I have ~0 interest in adding support for it.

I know that's not the answer you want to hear :/ But a vanishingly small number of people want to support Python 3.6 in October 2022.

**Comment by printdhruv** [comment]
@indygreg so in general is there any other route to accomplish this ? so for a ubuntu is it it possible to build any python 3.x using ./configure with required flags ? Is it possible to distribute binary this way ?
