### ISSUE TITLE
Building with OpenSSL 3.0 for the GitHub Release binaries

### ISSUE THREAD

**Issue by Edward-Knight** [indygreg/python-build-standalone#175]
[OpenSSL 1.1.1 is going EOL in September](https://www.openssl.org/blog/blog/2023/06/15/1.1.1-EOL-Reminder/), and it looks like the builds here are currently using [1.1.1s](https://github.com/indygreg/python-build-standalone/blob/85923ca3911784e6978b85d56e06e9ae75cb2dc4/pythonbuild/downloads.py#L207).
From a quick glance it seems like [CPython supports building with OpenSSL 3.0 from 3.9 onwards](https://github.com/python/cpython/issues/83001).

I was wondering if there were any plans about upgrading? I imagine Python 3.8 will still need to use OpenSSL 1.1.1, but I believe the other builds can be upgraded. I can help with an MR if there isn't anything blocking.

**Comment by indygreg** [comment]
We should ideally migrate to OpenSSL 3 for every CPython version that supports it. This has been on my mind for a while I just haven't done it yet.

On Windows, we might want to maintain parity with whatever CPython is shipping. i.e. we'll want to wait on upstream to ship a CPython 3.9 using OpenSSL before we do. (I anticipate CPython will run into issues getting OpenSSL 3 working right on Windows because pretty much nobody builds CPython from source on Windows and the build configurations that aren't identical to the official CPython releases aren't well tested.) But if CPython does have OpenSSL 3 test coverage, by all means upgrade.

Patches would be very much appreciated!

**Comment by erlend-aasland** [comment]
Also, the macOS installer uses the following:

https://github.com/python/cpython/blob/04492cbc9aa45ac2c12d22083c406a0364c39f5b/Mac/BuildScript/build-installer.py#L243-L256

**Comment by Edward-Knight** [comment]
OpenSSL has changed license in 3.0 to Apache License 2.0, which I assume isn't an issue but I'll note it here as it will require an update to the license info we bundle: https://www.openssl.org/source/license.html

**Comment by erlend-aasland** [comment]
FYI, OpenSSL 3.0.x is now used in the official binary builds: https://github.com/python/cpython/issues/99079#issuecomment-1657824684

**Comment by indygreg** [comment]
I think I'm pretty close to having OpenSSL 3.0 working. Just need to figure out how to handle a new dependency on libatomic on Linux.

On Linux and macOS I should be able to get OpenSSL 3.0 working across the board.

On Windows, I've only got OpenSSL 3.0 working on CPython 3.11. It looks like the latest CPython releases only support OpenSSL 3.0 in the Visual Studio build files on 3.11+. I'm guessing upstream will be backporting OpenSSL 3.0 Windows support to older CPython since OpenSSL 1.1 is EOL and the community will likely throw a fit if CPython ships OpenSSL 1.1 with known security vulnerabilities (once an unpatched vuln in 1.1 inevitably drops). I'm content waiting for upstream to provide official OpenSSL 3.x support before shipping it in python-build-standalone.

If someone knows what CPython is actually planning for OpenSSL 3 on Windows, please comment!

**Comment by erlend-aasland** [comment]
> If someone knows what CPython is actually planning for OpenSSL 3 on Windows, please comment!

Official CPython binaries from python.org are now using OpenSSL 3 for Windows builds (for the `main`, `3.12`, and `3.11` branches).

**Comment by indygreg** [comment]
> Official CPython binaries from python.org are now using OpenSSL 3 for Windows builds (for the `main`, `3.12`, and `3.11` branches).

I realize this.

But CPython <3.11 are still in support. And OpenSSL 1.1 is out of support. So what's CPython's plans for OpenSSL 3.x on <3.11? Or put another way, what is CPython going to do when an OpenSSL 1.1 vulnerability drops? Are CPython <3.11 going to remain exposed? Is CPython going to distribute a patched OpenSSL 1.1?

**Comment by erlend-aasland** [comment]
Quoting https://github.com/python/cpython/issues/99079#issuecomment-1694100406:

> None: binaries are no longer produced for these versions, and the code is already compatible (enough).

I think that answers most of your questions.
