### ISSUE TITLE
Linux Docker images used in GitHub Actions could be cached to avoid rebuilding daily

### ISSUE THREAD

**Issue by Edward-Knight** [indygreg/python-build-standalone#179]
This change is designed to help resolve #177, see for more details.

The image builds are unreliable, but we can just build these once and cache them instead of repeatedly rebuilding.
The [GitHub's Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) should work well for this.

**Comment by indygreg** [comment]
This is implemented in 8c4f5682925169408c02993e53e14960de4df14e. We don't push the full image to GHCR - just the cache. But the cache is sufficient to make CI builds work.

As a follow-up we could probably publish the full image to GHCR and set up the in-repo image build to use it. But I didn't want to cross this bridge because the image caching relies on BuildKit features that a lot of end-users may not have yet.
