### ISSUE TITLE
Include libffi in Windows image

### ISSUE THREAD

**Issue by jayvdb** [indygreg/python-build-standalone#23]
Branching off from https://github.com/indygreg/python-build-standalone/issues/22

Currently the Windows image provides some libffi symbols in `./python/build/extensions/_ctypes/ffi.obj` and `cfield.obj` , but it doesnt provide libffi as a separate library like mac and linux images.

This means it is troublesome for any project to use libffi (which is indirectly almost all serious Python projects via `cffi`), as doing so will cause linker conflicts.

**Comment by indygreg** [comment]
Fun fact: CPython's MSVC build has the libffi sources compiled directly into the `_ctypes` extension. That's why the object files defining libffi symbols are associated with that extension.

It is certainly possible to split libffi into its own library from the perspective of the distribution. And to be honest, I'm not sure why CPython's build system doesn't do this. Maybe it is because they have patched libffi and don't want to expose this patched version to consumers?

There are a handful of subtle gotchas stemming from linking libffi/ctypes statically on Windows. This is easily one of the most fragile parts of the Windows build. It also seems to be creating a lot of downstream packaging/linking problems...

**Comment by jayvdb** [comment]
https://bitbucket.org/cffi/cffi/issues/435/msvc-with-external-libffi-support gives some useful hints.

**Comment by jayvdb** [comment]
CPython 3.8 does use a recent libffi.

For the standalone builds of CPython 3.7, perhaps the "old hacked libffi" symbols in _ctypes can be renamed to avoid conflict?  Note the cffi copy of libffi is also old and hacked, but slightly different to the CPython one.  Likely periodically sync'd and currently slightly out of sync.

**Comment by indygreg** [comment]
I think I'm going to say this isn't worth doing. Providing a more traditional shared library based distribution on Windows will solve this problem and so much more. We can potentially revisit this solution in the future.
