### ISSUE TITLE
No static library available for macOS

### ISSUE THREAD

**Issue by genericptr** [indygreg/python-build-standalone#24]
This is more of a question but I wasn't sure how to contact the author any other way. 

I've built for macOS but I'm not seeing there is a static library available. I need an absolute barebones Python 3.x library for use as a scripting bridge in my program. No other packages are needed. Is this possible using your project?
 
Thank you for your time.

**Comment by indygreg** [comment]
It might be technically possible to produce a fully statically linked Python library on macOS. `python-build-standalone` does currently have some dependencies on system frameworks. However, the system frameworks that Python itself (ignoring some extensions) uses have been present on macOS for ages and there shouldn't be a problem running a binary on older macOS systems. Since the macOS execution environment is pretty consistent (like Windows but unlike Linux), I view fully static binaries as more trouble than they are worth. Is there a use case where a fully static library (without system framework dependencies) would be justified?

Also, we currently build with `MACOSX_DEPLOYMENT_TARGET=10.9`, meaning we only have binary compatibility down to Mavericks. It should be possible to go lower. But given macOS adoption curves, I'm not sure it is worth it: you are talking about a sliver of the overall macOS population still on <=10.8. I'd probably accept patches if they didn't compromise performance on modern macOS users (perhaps we'd have a separate macOS distribution for ancient OS versions). But it likely isn't something I'll take on myself.

**Comment by genericptr** [comment]
Relying of system frameworks is no problem. I just wanted to reduce the size of the binary since I've got such a minimal usage. I tested on macOS but I need Windows/Linux also.

**Comment by indygreg** [comment]
The distributions we build do not contain an explicit static library. However, static libraries on UNIX-like systems are effectively collections of object files (produced via the `ar` tool). One could construct a static library by parsing the `PYTHON.json` file for all object files and then putting those in an archive. This is effectively what PyOxidizer does. That shouldn't be more than a few dozen lines of Python. And that's a script we may want to commit to this repository, if written!

On Windows, a fully static binary is likely out of the question for much the same reasons as macOS (reliance on always-present system libraries, which is no big deal). But outside of system libraries, you can definitely produce a static Python install (with caveats: search issues for terms like `libffi`).

On Linux, it is possible to produce a fully statically linked binary with no shared library dependencies, not even libc (if building with musl libc).

PyOxidizer's code for linking a custom Python lives at https://github.com/indygreg/PyOxidizer/blob/e50a704fc778db9222e70b7ad4b08f68178483b5/pyoxidizer/src/py_packaging/libpython.rs#L142. The logic is pretty straightforward. And the `cc` crate is simply abstracting over toolchain differences. It all pretty much boils down to invoking `ar` (or its equivalent) with a computed set of object files.

**Comment by indygreg** [comment]
I think the questions posed in this issue were addressed. So closing.
