### ISSUE TITLE
What is the actual license of this project?

### ISSUE THREAD

**Issue by d3dave** [indygreg/python-build-standalone#297]
The LICENSE file is BSD 3-clause, but some build scripts contain an MPL notice.

**Comment by indygreg** [comment]
Valid call out on this report! Thank you.

The distributed artifacts have a myriad of licenses. We try to capture the license of the source projects and concatenate them together in the distributed artifacts.

The license of the code unique to this project has MPL 2.0 headers, as you noticed. But the `LICENSE` in the root directory is BSD 3-clause.

This project had its genesis due to the PyOxidizer project, which is MPL licensed. In the very beginning of the project both code bases did exist under the same repository. However, I don't think I ever published this repository and I effectively split the projects before publishing either.

I wanted PyOxidizer to have weak copyleft protections to promote open source ideals. This project likely inherited the MPL headers from when they were the same project and I was slapping MPL headers on every file I authored.

The failure to publish the correct MPL license for this project looks like a legit mistake on my part. It should be MPL 2.0.

We should correct the license file in the repository to reflect MPL 2.0.

If there are compelling reasons to switch off MPL for this project, we can entertain those in another issue. But be forewarned that enough people have contributed that it may entail a drawn out relicensing song and dance. So unsure how feasible that will be.
