### ISSUE TITLE
Improve Windows build process

### ISSUE THREAD

**Issue by uranusjr** [indygreg/python-build-standalone#4]
A couple of things I have in mind, will send a PR if I am successful in implementing them:

* Use [Strawberry Perl](http://strawberryperl.com/releases.html) to build OpenSSL, instead of depending on the `PERL` environment variable. Strawberry Perl has a nice portable distribution.
* Automatically set environment variables *a la* distutils, so I don’t forget to run `vcvarsall.bat` before building.

**Comment by indygreg** [comment]
These improvements are very much appreciated!

The Windows build is the least tested of the 3 and definitely the hackiest due to Visual Studio project file rewriting. (Linux is most tested.)

I spent way too many hours trying to get the Windows build working. When it finally reached a point that I was able prove the viability of PyOxidizer on Windows, I took a break. Depending on how far down the rabbit hole you go, you may find that various build settings aren't yet correct for standalone binaries. e.g. I believe we still need to tweak which C runtime to use and there may be some lingering DLL dependencies that can be eliminated.

But improvements to the build to make it more turnkey are very much welcome!

**Comment by indygreg** [comment]
This issue doesn't appear actionable, so closing.
