### ISSUE TITLE
Readline/editline linking or licence issue?

### ISSUE THREAD

**Issue by hakostra** [indygreg/python-build-standalone#58]
According to the docs:
https://python-build-standalone.readthedocs.io/en/latest/technotes.html

> On Linux, we statically link a libedit we compile ourselves, which is compiled against a libncurses we build ourselves.

When I for example try Python from package "cpython-3.7.9-x86_64-unknown-linux-gnu-pgo-20200823T0036" and do:
```
>>> import readline
>>> print(readline.__doc__)
>>> Importing this module enables command line editing using GNU readline.
```
it is evident that the build was actually linked with GNU Readline and not editline as the docs said.

As far as I can see this GNU Readline the only GPL-code linked into the Python build, which is a pity. If this behaviour is desired it would be nice if at least the documentation was updated (possibly also with a simple how-to on how to re-link Python).

**Comment by indygreg** [comment]
Modern distributions have both a `readline` Python extension built against readline and libedit. However, the default extension - and the one in the `python/install` directory which is statically linked into libpython - is using readline because this is the default for Python on Linux. Only Python on macOS officially supports libedit (you have to hack source code to get the extension to build with libedit on Linux).

So the documentation you referenced is in fact _wrong_. It is possible to link a libedit version of the extension by using the `python/build/Modules/VARIANT-readline-libedit-readline-libedit.o` file along with linking `python/build/lib/libedit.a` and `build/lib/libncursesw.a`. But this isn't straightforward with code available today. PyOxidizer should eventually get to the state where it can be used to produce a custom libpython, without the GPL code encumbering usage.

**Comment by hakostra** [comment]
Thanks for efficient reply!
