### ISSUE TITLE
Static python lib build?

### ISSUE THREAD

**Issue by toastersocks** [indygreg/python-build-standalone#73]
On macOS, is there a way to build a static python lib (lib/libpython3.9.a) instead of the dynamic python lib (lib/libpython3.9.dylib) this produces by default? I need a static lib for my use-case. When building python the "regular" way, if the shared option is not specified to the configure script, then a static lib is produced by default. 
I've looked through the [docs](https://python-build-standalone.readthedocs.io), but I can't find anything about this.
Is there any way to get this to create a static python lib?
Thanks,

James

**Comment by anki-code** [comment]
This question is interesting for me too.

I have a building scripts to build portable [xonsh shell](https://xon.sh) - [xonsh-portable-binary](https://github.com/anki-code/xonsh-portable-binary) that based on Alpine (to have musl on board) and [nuitka](https://github.com/Nuitka/Nuitka/). And to compile statically linked portable xonsh I need statically linked `libpython3.8.a`.

For now I'm using [python-cmake-buildsystem](https://github.com/python-cmake-buildsystem/python-cmake-buildsystem) but it has no updates since Python 3.6. Here is [how I did it](https://github.com/anki-code/xonsh-portable-binary/blob/4af3f598899d66a63de28c6cc402d9444783788f/xonsh-portable-musl-alpine.Dockerfile#L14-L22).

After reading #57 I understand that there is a way to build the same with python-build-standalone but I'm not so experienced in building to do it.

@indygreg could you please share the way to build statically linked Python using python-build-standalone?

Thanks!

**Comment by indygreg** [comment]
We don't currently include a static libpython in the macOS distributions. Although we probably could, as I believe CPython's build system produces it.

There is enough data in the distributions today to create your own static libpython, however. A `.a` file is simply a tar-like archive file containing the object files constituting the library. If you use the `ar` program to create a `.a` file from all the `.o` files in the `python/build/` directory tree, you effectively have the same static library that the build system would produce.

**Comment by indygreg** [comment]
Oh, sorry - we do ship the static libpython: it's just in a path like `python/install/lib/python3.9/config-3.9-darwin/libpython3.9.a` instead of `lib/libpython3.9.a`. We could add a symlink to the distributions so the more obvious path exists.
