### ISSUE TITLE
ctypes module is unusable in aarch64-apple-darwin builds

### ISSUE THREAD

**Issue by vadimcn** [indygreg/python-build-standalone#76]
Attempt to create a Python function wrapper results in a MemoryError.
Seems to be a manifestation of [this bug](https://bugs.python.org/issue42688).

Repro:
1. Download and extract one of aarch64-apple-darwin archives. (I used cpython-3.9.2-aarch64-apple-darwin-pgo-20210327T1202.tar.zst)
2. Run test script from the linked bug.

**Comment by indygreg** [comment]
Thanks for the bug report. Looks legit.

**Comment by indygreg** [comment]
I was able to reproduce the `MemoryError` on my M1. And I was able to verify the test case works after the just-committed change. I did manage to trigger some segfaults along the way due to bad combinations of preprocessor defines (notably `USING_MALLOC_CLOSURE_DOT_C=1` missing). But I believe the logic in our static config files match `setup.py`'s now and we should be good to go.

I'll likely roll a new release for 3.9.3 in the next day or two. This fix should ride along.
