### ISSUE TITLE
Other pythons versions

### ISSUE THREAD

**Issue by erdnaxeli** [indygreg/python-build-standalone#8]
This is more a question than an actual issue: is it planned to build other versions of Python? Python 3.4 is now deprecated but some project may still be using it (I am :disappointed: ), and 3.5 and 3.6 versions would be great.

3.7 introduced the `async` keyword so it is not a drop in replacement to previous version, and my projects with which I wanted to try PyOxidizer need some work before being able to use python 3.7…

Anyway, I'm very excited by this project!

**Comment by indygreg** [comment]
3.5 and 3.6 support should be technically viable. I was holding out hope that we could avoid the overhead of maintaining distributions for these versions because 3.7 is typically a drop-in replacement for 3.5 and 3.6. But I've been around enough Python to know there are real reasons people lag behind a major version or two.

I'm quite busy with other PyOxidizer work at the moment. I suspect it may be more practical for you to invest in 3.7 support than to wait for me to produce 3.5 or 3.6 distributions. I wouldn't at all be surprised if I produce a 3.8 distribution before 3.7 (I need to test 3.8 for compatibility with PyOxidizer before it gets too late in the 3.8 release process to make changes).

**Comment by daphil19** [comment]
I may be missing something, but would support for these versions be as simple as modifying `downloads.py` to contain targets for these versions?

**Comment by indygreg** [comment]
We would need an entry in `downloads.py` and then various code paths in the per-platform `.py` build scripts would need to be taught to take the Python version as an argument. You'd likely want to add a command line argument to define which version to build. Finally, I anticipate that some of the patches we apply to CPython will fail to apply on Python 3.5 or 3.6. So we may need to make Python patching conditional on the Python version being used.

**Comment by indygreg** [comment]
I pushed some commits today that mostly parameterize the Python version. So you can pass an argument into `build-linux.py` to control which Python distribution to build.

However, I only implemented this on Linux. A solution for macOS should look very similar.

And, I only added support for Python 3.8. I did experiment with Python 3.6, but it failed due to low-level build system wonkiness. It is probably a solvable problem. I'm not sure when I'll have time to look at it more.

**Comment by indygreg** [comment]
I'm actively working on Python 3.8 support.

I do not think supporting Python < 3.7 is a worthwhile effort. So I'm closing this issue.
