### ISSUE TITLE
Skip packaging regression tests?

### ISSUE THREAD

**Issue by kornholi** [indygreg/python-build-standalone#9]
Currently all of the regression tests are being packaged. It adds up to quite a bit of space:
```
21M     install/lib/python3.7/test
```

My debian installation only has a small subset:
```
$ du -sh /usr/lib/python3.7/test
516K    /usr/lib/python3.7/test
$ tree /usr/lib/python3.7/test
/usr/lib/python3.7/test
├── __init__.py
├── __main__.py
├── __pycache__
│   ├── __init__.cpython-37.pyc
│   ├── __main__.cpython-37.pyc
│   ├── ann_module.cpython-37.pyc
│   ├── ann_module2.cpython-37.pyc
│   ├── ann_module3.cpython-37.pyc
│   ├── regrtest.cpython-37.pyc
│   └── test_support.cpython-37.pyc
├── ann_module.py
├── ann_module2.py
├── ann_module3.py
├── libregrtest
│   ├── __init__.py
│   ├── __pycache__
│   │   ├── __init__.cpython-37.pyc
│   │   ├── cmdline.cpython-37.pyc
│   │   ├── main.cpython-37.pyc
│   │   ├── refleak.cpython-37.pyc
│   │   ├── runtest.cpython-37.pyc
│   │   ├── runtest_mp.cpython-37.pyc
│   │   ├── save_env.cpython-37.pyc
│   │   ├── setup.cpython-37.pyc
│   │   └── utils.cpython-37.pyc
│   ├── cmdline.py
│   ├── main.py
│   ├── refleak.py
│   ├── runtest.py
│   ├── runtest_mp.py
│   ├── save_env.py
│   ├── setup.py
│   └── utils.py
├── regrtest.py
├── support
│   ├── __init__.py
│   ├── __pycache__
│   │   ├── __init__.cpython-37.pyc
│   │   ├── script_helper.cpython-37.pyc
│   │   └── testresult.cpython-37.pyc
│   ├── script_helper.py
│   └── testresult.py
└── test_support.py

5 directories, 38 files
```

However this seems to be different everywhere I look...

The docker images don't have it at all:
```
$ docker run --rm -it python:3.7 python -c "import test"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'test'
```

But my macOS homebrew install includes everything:
```
 20M	/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/test/
```

**Comment by indygreg** [comment]
Yeah, the test modules don't have much value and I remember debating whether to include them (as well as other potentially lesser value modules). I decided to keep them so that the Python distribution would remain _fully featured_. This could facilitate e.g. running the Python unit tests from the distribution or a repackaged version of it. Although I concede I've never actually done this.

On Linux, I produced a `.tar.zst` with the `test/` directory removed and the resulting archive was `38,248,649` bytes instead of `45,668,424`. Smaller, yes. But we're only talking about a few MB. I could probably shave that many bytes off by tweaking the zstandard compression parameters.

Is your concern here more the archive size or the presence of the files? If its the presence of the files, assuming you found this project via PyOxidizer, should PyOxidizer treat test files differently to lead to a better experience?

**Comment by kornholi** [comment]
Right, but perhaps it's enough to run those tests after building? I assume there are no cases where'd you expect them to fail.

I'm not really concerned about this too much, just surprised how big it was and did some digging. While it might be a few MB, it's still a 16% decrease. It also brings down the total count of files from 3047 to 2016.

There are a few other opportunities: symlinking `install/lib/python3.7/config-3.7m-x86_64-linux-gnu/libpython3.7m.a` to `install/lib/libpython3.7m.a` shaves off another 8MB from the `.tar.gz` for me. Same can be done with `libdb-6.0.a` and `libdb.a` (do we actually need both?). In the end the uncompressed size decreased by 26%, which is pretty substantial. 

I'm using these builds to provide an identical interpreter for all developers of our code base (monorepo managed with Bazel) instead of trying to support whatever they have installed locally. So far it's been working great and solved several long-standing headaches.

**Comment by indygreg** [comment]
I just made some compression settings changes that reduce the Linux archive size from ~49 MB to ~24 MB. Given the new compression settings, I'm not sure it is worth pruning tests from the archive itself. If there's any optimization, it would be to skip extracting tests.

**Comment by indygreg** [comment]
Given how small the archives are now, I'm not sure removing the test modules makes much sense. So I'm going to close this.

**Comment by kornholi** [comment]
Thank you!
